# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run build

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: release-${{ steps.package-version.outputs.current-version}}
        files: |
          extension/ttl-enhance-chrome.zip
          extension/ttl-enhance-firefox.xpi
          extension/ttl-enhance-opera.crx
      
    - name: Release on Firefox AddOns Store
      uses: trmcnvn/firefox-addon@v1
      with:
        # uuid is only necessary when updating an existing addon,
        # omitting it will create a new addon
        uuid: '{b9752293-d8d4-4e26-8f7c-f174e220eb03}'
        xpi: extension/ttl-enhance-firefox.xpi
        manifest: extension/firefox/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
          

    